SUPABASE_URL = "https://xqjqanyjvtcduvaicleo.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxanFhbnlqdnRjZHV2YWljbGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwNTY0MzQsImV4cCI6MjEwNTYzMjQzNH0.pwiY9yKUHucQWIwfvWeXfsG2D5UwdB8j4nbdF9ds18k"

BASE44_URL = "https://app.base44.com/api/agents/6ab2ab29f1412650a6783b8b"
BASE44_TOKEN = "b44u_4bd5d172dfd5aba27104aa18b01e1be2420f8771748ceadd16a250e36ed16596"
